### ISSUE TITLE
linux/texlive build is not working after #34359c7 commit

### ISSUE THREAD

**Issue by melias122** [Kyslik/FEIStyle#15]

**Comment by Kyslik** [comment]
Yes, its breaking change try building vanilla [v1.5.1](https://github.com/Kyslik/FEIStyle/releases/tag/1.5.1) with make.

Report any issues.

**Comment by Kyslik** [comment]
Or master

https://github.com/Kyslik/FEIStyle/archive/master.zip

**Comment by melias122** [comment]
It's not working. I attached build directory with logs.
[build.zip](https://github.com/Kyslik/FEIStyle/files/838243/build.zip)

**Comment by Kyslik** [comment]
please run

```
$ tex --version
```

report back

**Comment by melias122** [comment]
seems like glossaries did all problems, solved in https://github.com/melias122/FEIStyle/commit/d014a8fb6ff1fcc4b9f3180db75e0108548efc74.

I also cleaned up Makefile

**Comment by Kyslik** [comment]
Fixed in master (https://github.com/Kyslik/FEIStyle/commit/a6a23d55eba8e69d8d5757ef5dbba1c3ada11e1f)

**Comment by melias122** [comment]
confirmed, it works now
