### ISSUE TITLE
List of Glossaries not working

### ISSUE THREAD

**Issue by jarosevcik** [Kyslik/FEIStyle#29]
List of glossaries is not printed in .pdf even for the fresh, not changed project. Tried on MacOs Big Sur and also online in overleaf.  References to acronyms is working correctly(e.g. \acrshort{my_awesome_short}).  Example value from glossary.tex 
\newacronym{mfa}{MFA}{My Fancy Acronym}. No error found during compilation.

**Comment by matusjokay** [comment]
What exactly is not working? Just now I tried master branch (the latest commit 1ac71d8d51b) on Overleaf (with the `example.tex` source file) and everything seems to be ok... both english and slovak version, too.

Note 1: `FEIstyle.cls` defines (on the line No. 609) the name of list of glossaries as 'List of Abbreviations'.
Note 2: List of glossaries shows only referenced acronyms. So, if You define some acronym in `glossary.tex`, e.g. `\newacronym{mfa}{MFA}{My Fancy Acronym}`, but this acronym is never referenced with `\acrshort{mfa}` or `\acrfull{mfa}` command, it is not shown in the List of Abbreviations.

**Comment by matusjokay** [comment]
Issue closed, see #25 for solution.
